version: "3.9"

services:
  pihole-unbound:
    container_name: pihole
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53"
      #- "67:67" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      WEBPASSWORD: ${WEBPASSWORD}
      TZ: ${TZ:-UTC}
      DNS1: 127.0.0.1#5335 # Primary upstream DNS provider
      DNSSEC: "true"
      DNSMASQ_LISTENING: single
    volumes:
      - './etc/pihole:/etc/pihole'
      - './etc/dnsmasq.d:/etc/dnsmasq.d'
      - './etc/unbound/unbound.conf.d/pi-hole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf'
    cap_add:
      - NET_ADMIN
